version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: url
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    #command: bash -c "cd app/database && alembic upgrade head && cd ../.. && python app/main.py"
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://user:pass@mysql:3306/url
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data
    depends_on:
      - mysql
    networks:
      - backend_network
      - mysql_network

  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend_network
      - mysql_network
      - frontend_network

  deployment:
    build:
      context: ./deployment
      dockerfile: ./Dockerfile
    #command: bash -c "cd app/database && alembic upgrade head && cd ../.. && python app/main.py"
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - deployment_data:/app/data
    networks:
      - backend_network

networks:
  mysql_network:
  backend_network:
  frontend_network:

volumes:
  mysql_data:
  backend_data:
