"""add_url_limit

Revision ID: 367cca26c490
Revises: 0e576fa0c44b
Create Date: 2023-11-12 13:46:03.620589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367cca26c490'
down_revision: Union[str, None] = '0e576fa0c44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('short_url_access_log_ibfk_1', 'short_url_access_log', type_='foreignkey')
    op.create_foreign_key(None, 'short_url_access_log', 'short_urls', ['short_url_id'], ['id'], source_schema='url', referent_schema='url')
    op.add_column('short_urls', sa.Column('url_use_limit', sa.Boolean(), nullable=True))
    op.drop_constraint('short_urls_ibfk_1', 'short_urls', type_='foreignkey')
    op.create_foreign_key(None, 'short_urls', 'users', ['user_id'], ['id'], source_schema='url', referent_schema='url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_urls', schema='url', type_='foreignkey')
    op.create_foreign_key('short_urls_ibfk_1', 'short_urls', 'users', ['user_id'], ['id'])
    op.drop_column('short_urls', 'url_use_limit')
    op.drop_constraint(None, 'short_url_access_log', schema='url', type_='foreignkey')
    op.create_foreign_key('short_url_access_log_ibfk_1', 'short_url_access_log', 'short_urls', ['short_url_id'], ['id'])
    # ### end Alembic commands ###
