"""modify_short_urls_table

Revision ID: 9526e4beaafa
Revises: 367cca26c490
Create Date: 2023-11-12 18:17:15.105452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9526e4beaafa'
down_revision: Union[str, None] = '367cca26c490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('short_url_access_log_ibfk_1', 'short_url_access_log', type_='foreignkey')
    op.create_foreign_key(None, 'short_url_access_log', 'short_urls', ['short_url_id'], ['id'], source_schema='url', referent_schema='url')
    op.drop_constraint('short_urls_ibfk_1', 'short_urls', type_='foreignkey')
    op.create_foreign_key(None, 'short_urls', 'users', ['user_id'], ['id'], source_schema='url', referent_schema='url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_urls', schema='url', type_='foreignkey')
    op.create_foreign_key('short_urls_ibfk_1', 'short_urls', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'short_url_access_log', schema='url', type_='foreignkey')
    op.create_foreign_key('short_url_access_log_ibfk_1', 'short_url_access_log', 'short_urls', ['short_url_id'], ['id'])
    # ### end Alembic commands ###
